## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv(r"D:\debu\My study interests\Cascade 2020 Dataset\train_age_dataset - Copy.csv")
data = pd.read_csv(r'D:\debu\My study interests\Cascade 2020 Dataset\test_age_dataset.csv')

## Handling of Outliers

In [ ]:
dataset.loc[[187399],['avgTimeSpent']]=dataset.avgTimeSpent.max()
dataset.loc[[476092],['avgTimeSpent']]=dataset.avgTimeSpent.max()

## Assigning of values

In [3]:
X = dataset.iloc[:,0:-1].values
y = dataset.iloc[:,-1].values

In [4]:
X_test1 = data.iloc[:,0:26].values

## Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=147)

## Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,[13,14,25]] = sc.fit_transform(X_train[:,[13,14,25]])
X_test[:,[13,14,25]] = sc.transform(X_test[:,[13,14,25]]) 
X_test1[:,[13,14,25]] = sc.transform(X_test1[:,[13,14,25]])

## Training the XG Boost Classifier on the Training set

In [7]:
from xgboost import XGBClassifier
XGB = XGBClassifier(learning_rate=0.15, max_depth=12, min_child_weight=8, 
                    eta=3, n_estimators=350, 
                    penalty="l1", random_state=856) # 93.2
XGB.fit(X_train,y_train)


C:\Users\DELL\Anaconda3\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[20:33:55] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:541: 
Parameters: { penalty } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[20:33:58] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, eta=3, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.15, max_delta_step=0, max_depth=12,
              min_child_weight=8, missing=nan, monotone_constraints='()',
              n_estimators=350, n_jobs=4, num_parallel_tree=1,
              objective='multi:softprob', penalty='l1', random_state=856,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', use_label_encoder=True,
              validate_parameters=1, verbosity=None)

## Predicting the test set results

In [ ]:
y_pred = XGB.predict(X_test)
y_pred1 = XGB.predict(X_test1)

## Checking the accuracy and f1_score for the predicted results

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))
from sklearn.metrics import f1_score
print(f1_score(y_test, y_pred, average='weighted'))

[[58313  1526  1209   591]
 [ 1148  9182   930   632]
 [ 1302  1750  7850  1244]
 [ 2162  1882  3812  4243]]
0.8139829815087547
0.8063744420846554


## Creating the dataframe and saving the pediction as a csv file

In [9]:
df = pd.DataFrame(y_pred1, columns=['prediction'])
df.to_csv('Cascade_final1.csv', header = True, index=False)